FROM docker.io/node:16-alpine3.12 AS builder

COPY . /client
WORKDIR /client

RUN npm i pnpm@7 -g
RUN pnpm install
RUN CI=false pnpm build:testing

FROM nginx:stable
EXPOSE 3000
COPY --from=builder /client/dist /usr/share/nginx/html
COPY --from=builder /client/container/nginx.conf /etc/nginx/
COPY --from=builder /client/container/default.conf /etc/nginx/conf.d/