/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155 } from './ERC1155';
export * as factories from './factories';
export { ERC1155__factory } from './factories/ERC1155__factory';
